const mongoose = require('mongoose');
const { Schema } = mongoose;
const db = require("../config/db");

const driverSchema = new Schema({
    licenseNumber: String,
    name: String,
    mobileNumber: String,
    driverImage: String,
    temporaryAddress: String,
});

const vehicleSchema = new Schema({
    ownerName: String,
    vehicleClassDesc: String,
    model: String,
    bodyType: String,
    engineNumber: String,
    chassisNumber: String,
    manufacturerName: String,
    vehicleInsuranceValidity: String,
    roadPermitValidity: String,
    fitnessPermitValidity: String,
    puccValidity: String,
});

const addVehicleSchema = new Schema({
    vehicleDetails: vehicleSchema,
    driverDetails: driverSchema
});

const DriverDetailsSchema = new Schema({
    nationality: String,
    dl_no: String,
    dob: String,
    name: String,
    relationShip: String,
    gender: String,
    blood_group: String,
    gender: String,
    permanent_address: String,
    temporary_address: String,
    cov: String,
    image: String,
    mobile_number: String,
    issue_date: String,
});

const VehicleDetailsSchema = new Schema({
    status: String,
    message: String,
    response_type: String,
    result: {
        state_code: String,
        state: String,
        office_code: Number,
        office_name: String,
        reg_no: String,
        reg_date: String,
        purchase_date: String,
        owner_count: Number,
        owner_name: String,
        owner_father_name: String,
        current_address_line1: String,
        current_address_line2: String,
        current_address_line3: String,
        current_district_name: String,
        current_state: String,
        current_state_name: String,
        current_pincode: Number,
        permanent_address_line1: String,
        permanent_address_line2: String,
        permanent_address_line3: String,
        permanent_district_name: String,
        permanent_state: String,
        permanent_state_name: String,
        permanent_pincode: Number,
        owner_code_descr: String,
        reg_type_descr: String,
        vehicle_class_desc: String,
        chassis_no: String,
        engine_no: String,
        vehicle_manufacturer_name: String,
        model_code: String,
        model: String,
        body_type: String,
        cylinders_no: Number,
        vehicle_hp: Number,
        vehicle_seat_capacity: Number,
        vehicle_standing_capacity: Number,
        vehicle_sleeper_capacity: Number,
        unladen_weight: Number,
        vehicle_gross_weight: Number,
        vehicle_gross_comb_weight: Number,
        fuel_descr: String,
        color: String,
        manufacturing_mon: Number,
        manufacturing_yr: Number,
        norms_descr: String,
        wheelbase: Number,
        cubic_cap: Number,
        floor_area: Number,
        ac_fitted: String,
        audio_fitted: String,
        video_fitted: String,
        vehicle_purchase_as: String,
        vehicle_catg: String,
        dealer_code: String,
        dealer_name: String,
        dealer_address_line1: String,
        dealer_address_line2: String,
        dealer_address_line3: String,
        dealer_district: String,
        dealer_pincode: String,
        sale_amount: Number,
        laser_code: String,
        garage_add: String,
        length: Number,
        width: Number,
        height: Number,
        reg_upto: String,
        fit_upto: String,
        annual_income: Number,
        op_dt: String,
        imported_vehicle: String,
        other_criteria: Number,
        status: String,
        vehicle_type: String,
        tax_mode: String,
        mobile_no: Number,
        email_id: String,
        pan_no: String,
        aadhar_no: String,
        passport_no: String,
        ration_card_no: String,
        voter_id: String,
        dl_no: String,
        verified_on: String,
        dl_validation_required: Boolean,
        condition_status: Boolean,
        vehicle_insurance_details: {
            insurance_from: String,
            insurance_upto: String,
            insurance_company_code: Number,
            insurance_company_name: String,
            opdt: String,
            policy_no: String,
            vahan_verify: String,
            reg_no: String,
        },
        vehicle_pucc_details: {
            pucc_from: String,
            pucc_upto: String,
            pucc_centreno: String,
            pucc_no: String,
            op_dt: String,
        },
        permit_details: {
            appl_no: String,
            pmt_no: String,
            reg_no: String,
            rcpt_no: String,
            purpose: String,
            permit_type: String,
            permit_catg: Number || String ,
            permit_issued_on: String,
            permit_valid_from: String,
            permit_valid_upto: String,
        },
        latest_tax_details: {
            reg_no: String,
            tax_mode: String,
            payment_mode: String,
            tax_amt: Number,
            tax_fine: Number,
            rcpt_dt: String,
            tax_from: String,
            tax_upto: String,
            collected_by: String,
            rcpt_no: String,
        },
        financer_details: {
            hp_type: String,
            financer_name: String,
            financer_address_line1: String,
            financer_address_line2: String,
            financer_address_line3: String,
            financer_district: String,
            financer_pincode: Number,
            financer_state: String,
            hypothecation_dt: String,
            op_dt: String,
        },
    },
});

const VehicleModel = db.model('Vehicle', addVehicleSchema);
module.exports = {VehicleDetailsSchema, DriverDetailsSchema, VehicleModel}
